"use client";

import { FormEvent, KeyboardEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";

type Snapshot = { connected: Record<string, boolean>; tasks: { id:number; title:string; done:boolean; due?:string }[]; shopping:{id:string;title:string;checked:boolean}[]; meal:{title:string;note:string;slug?:string}|null; things:{id:string;name:string;quantity:number;type:string}[]; services:{name:string;connected:boolean;ok:boolean}[]; generatedAt:string };
type Space = "today"|"plan"|"home"|"cinema"|"library";
const empty:Snapshot={connected:{},tasks:[],shopping:[],meal:null,things:[],services:[],generatedAt:""};
const labels:Record<string,string>={mealie:"Кухня",vikunja:"Справи",homebox:"Речі"};
const spaces:{id:Space;label:string;icon:string}[]=[{id:"today",label:"Сьогодні",icon:"⌂"},{id:"plan",label:"План",icon:"✓"},{id:"home",label:"Дім",icon:"◇"},{id:"cinema",label:"Кіно",icon:"▷"},{id:"library",label:"Речі",icon:"□"}];

export function HomeDashboard(){
 const [data,setData]=useState(empty),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[composer,setComposer]=useState(false),[palette,setPalette]=useState(false),[drawer,setDrawer]=useState(false),[space,setSpace]=useState<Space>("today"),[kind,setKind]=useState("task.create"),[notice,setNotice]=useState(""),[lite,setLite]=useState(false),[query,setQuery]=useState("");
 const main=useRef<HTMLElement>(null);
 const refresh=useCallback(async()=>{try{const r=await fetch("/api/snapshot",{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());setOffline(false)}catch{setOffline(true)}finally{setLoading(false)}},[]);
 useEffect(()=>{const preference=setTimeout(()=>{const saved=localStorage.getItem("home-motion");setLite(saved==="lite"||(saved===null&&matchMedia("(pointer: coarse)").matches))},0);const kick=setTimeout(refresh,0),timer=setInterval(refresh,60000);return()=>{clearTimeout(preference);clearTimeout(kick);clearInterval(timer)}},[refresh]);
 useEffect(()=>{const key=(e:globalThis.KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}if(e.key==="Escape"){setPalette(false);setComposer(false);setDrawer(false)}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 useEffect(()=>{const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.08});document.querySelectorAll("[data-reveal]").forEach(el=>observer.observe(el));return()=>observer.disconnect()},[space,loading]);
 useEffect(()=>{main.current?.focus({preventScroll:true})},[space]);
 async function action(payload:Record<string,unknown>){const r=await fetch("/api/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),result=await r.json();if(!r.ok)throw new Error(result.error||"Не вдалося виконати дію");await refresh()}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const title=String(new FormData(e.currentTarget).get("title")||"").trim();if(!title)return;try{await action({action:kind,title});setNotice("Готово — дім оновлено");setComposer(false);e.currentTarget.reset()}catch(err){setNotice(err instanceof Error?err.message:"Сталася помилка")}setTimeout(()=>setNotice(""),3500)}
 async function toggle(id:number,done:boolean){setData(c=>({...c,tasks:c.tasks.map(t=>t.id===id?{...t,done}:t)}));try{await action({action:"task.toggle",id,done})}catch{await refresh();setNotice("Не вдалося змінити справу")}}
 const openComposer=(next="task.create")=>{setKind(next);setComposer(true)};
 const commands=useMemo(()=>[{label:"Додати справу",hint:"Vikunja",run:()=>openComposer("task.create")},{label:"Додати покупку",hint:"Mealie",run:()=>openComposer("shopping.create")},{label:"Додати річ",hint:"Homebox",run:()=>openComposer("thing.create")},...spaces.map(s=>({label:`Відкрити: ${s.label}`,hint:"Розділ",run:()=>setSpace(s.id)}))].filter(x=>x.label.toLowerCase().includes(query.toLowerCase())),[query]);
 const commandKey=(e:KeyboardEvent<HTMLButtonElement>,run:()=>void)=>{if(e.key==="Enter"){run();setPalette(false)}};
 const ready=data.services.filter(s=>s.ok).length, open=data.tasks.filter(t=>!t.done).length;
 const date=new Intl.DateTimeFormat("uk-UA",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 return <div className={lite?"app lite":"app"}>
  <a className="skip" href="#content">До вмісту</a><div className="ambient" aria-hidden="true"><i/><i/><i/></div>
  <aside className="rail" aria-label="Головна навігація"><a className="brand" href="#content" aria-label="Наш дім"><span>Д</span><b>Наш дім</b></a><nav>{spaces.map(s=><button key={s.id} className={space===s.id?"active":""} onClick={()=>setSpace(s.id)} aria-current={space===s.id?"page":undefined}><i>{s.icon}</i><span>{s.label}</span>{s.id==="cinema"&&<small>скоро</small>}</button>)}</nav><button className="utility" onClick={()=>setDrawer(true)}><span>•••</span><div><b>Системи</b><small>{ready}/3 онлайн</small></div></button></aside>
  <main id="content" className="workspace" ref={main} tabIndex={-1}>
   <header className="topbar"><div className="residents" aria-label="Мешканці"><span>Р</span><span>♡</span><p>Наш простір</p></div><div className="top-actions"><button onClick={()=>setPalette(true)} className="search">⌕ <span>Швидка команда</span><kbd>⌘ K</kbd></button><button className="motion" onClick={()=>{const next=!lite;setLite(next);localStorage.setItem("home-motion",next?"lite":"full")}} aria-pressed={lite}>{lite?"Рух: мін.":"Рух: повний"}</button><button className="avatar" onClick={()=>setDrawer(true)} aria-label="Відкрити системну панель">РС</button></div></header>
   {offline&&<div className="offline" role="alert"><b>Панель працює офлайн</b><span>Показуємо останні дані. Перевіримо сервер автоматично.</span><button onClick={refresh}>Спробувати зараз</button></div>}
   {space==="today"&&<Today data={data} loading={loading} date={date} ready={ready} open={open} toggle={toggle} add={openComposer} details={()=>setDrawer(true)}/>} 
   {space==="plan"&&<Plan data={data} loading={loading} toggle={toggle} add={openComposer}/>} 
   {space==="library"&&<Library data={data} loading={loading} add={openComposer}/>} 
   {(space==="home"||space==="cinema")&&<Coming space={space} goToday={()=>setSpace("today")}/>} 
  </main>
  {palette&&<div className="overlay" role="presentation" onMouseDown={()=>setPalette(false)}><section className="palette" role="dialog" aria-modal="true" aria-label="Швидкі команди" onMouseDown={e=>e.stopPropagation()}><label><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Що хочете зробити?"/></label><div>{commands.map((c,i)=><button key={c.label} autoFocus={i===0&&!query} onClick={()=>{c.run();setPalette(false)}} onKeyDown={e=>commandKey(e,c.run)}><span>{c.label}<small>{c.hint}</small></span><kbd>↵</kbd></button>)}{!commands.length&&<p className="no-results">Нічого не знайдено</p>}</div><footer>↑↓ обрати · Enter відкрити · Esc закрити</footer></section></div>}
  {composer&&<div className="overlay" onMouseDown={()=>setComposer(false)}><form className="composer" onSubmit={submit} onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><header><div><p>ШВИДКА ДІЯ</p><h2>Що додамо?</h2></div><button type="button" onClick={()=>setComposer(false)} aria-label="Закрити">×</button></header><div className="kind-tabs">{[["task.create","Справа"],["shopping.create","Покупка"],["thing.create","Річ"]].map(([v,l])=><button type="button" key={v} className={kind===v?"selected":""} onClick={()=>setKind(v)}>{l}</button>)}</div><input autoFocus name="title" aria-label="Назва" placeholder={kind==="task.create"?"Наприклад, забрати посилку":kind==="shopping.create"?"Наприклад, молоко":"Наприклад, гарантія на чайник"}/><button className="save">Додати до дому</button></form></div>}
  {drawer&&<aside className="drawer" aria-label="Системи дому"><header><div><p>СИСТЕМА ДОМУ</p><h2>Усе під контролем</h2></div><button onClick={()=>setDrawer(false)} aria-label="Закрити">×</button></header><div className="health">{data.services.map(s=><div key={s.name}><i className={s.ok?"on":"off"}/><span><b>{labels[s.name]}</b><small>{s.ok?"Працює":s.connected?"Потрібна увага":"Не підключено"}</small></span></div>)}</div><div className="drawer-links"><a href="https://vault.home.arpa">Vaultwarden <span>↗</span></a><a href="https://mealie.home.arpa">Mealie <span>↗</span></a><a href="https://vikunja.home.arpa">Vikunja <span>↗</span></a><a href="https://homebox.home.arpa">Homebox <span>↗</span></a></div><p className="synced">Остання синхронізація<br/><b>{data.generatedAt?new Date(data.generatedAt).toLocaleTimeString("uk-UA",{hour:"2-digit",minute:"2-digit"}):"—"}</b></p></aside>}
  {drawer&&<button className="drawer-shade" onClick={()=>setDrawer(false)} aria-label="Закрити панель"/>}{notice&&<div className="toast" role="status">{notice}</div>}
 </div>
}

function Today({data,loading,date,ready,open,toggle,add,details}:{data:Snapshot;loading:boolean;date:string;ready:number;open:number;toggle:(id:number,d:boolean)=>void;add:(k?:string)=>void;details:()=>void}){return <><section className="today-scene" aria-label="Огляд дому">
 <div className="home-hero" data-reveal data-depth="0"><div className="hero-light" aria-hidden="true"/><div className="hero-copy" data-depth="4"><p>{date}</p><h1>Спокійний ритм<br/><em>вашого дому.</em></h1><span>Усе важливе — поруч.</span><button className="add-main" onClick={()=>add()}><i>＋</i><span>Додати</span></button></div></div>
 <a className="dinner-feature" data-reveal data-depth="3" href={data.meal?.slug?`https://mealie.home.arpa/g/home/r/${data.meal.slug}`:"https://mealie.home.arpa"} aria-label="Відкрити план вечері"><Image src="/home-evening.jpg" alt="Паста з томатами на теплому вечірньому столі" fill sizes="(max-width: 900px) 100vw, 40vw" priority/><div><small>СЬОГОДНІ НА ВЕЧІР</small><h2>Вечеря удвох</h2><i/><p>{data.meal?.title||"Вечерю ще не обрано"}</p></div></a>
 <button className="pulse" onClick={details} data-reveal data-depth="4"><i>⌂</i><span><b>{ready===3?"Дім у порядку":"Потрібне підключення"}</b><small>{ready}/3 системи відповідають</small></span><div className="home-signals" aria-hidden="true"><i>◉</i><i>ϟ</i><i>⌁</i></div><strong>{open} відкритих справ　→</strong></button>
 </section><div className="grid lower-grid"><Panel title="Справи на сьогодні" eyebrow="СПІЛЬНИЙ ПЛАН" badge={`${open}`} className="tasks" loading={loading}><TaskList data={data} toggle={toggle}/></Panel><Panel title="Список покупок" eyebrow="MEALIE" action={()=>add("shopping.create")} loading={loading}>{data.shopping.filter(x=>!x.checked).length?<div className="chips shopping-tiles">{data.shopping.filter(x=>!x.checked).slice(0,8).map(x=><span key={x.id}>◌　{x.title}</span>)}</div>:<Empty text={data.connected.mealie?"Список порожній — чудовий знак":"Підключіть Mealie"}/>}</Panel><Panel title="Нові речі" eyebrow="HOMEBOX" action={()=>add("thing.create")} loading={loading}>{data.things.length?<Things data={data}/>:<Empty text={data.connected.homebox?"Тут з’являться ваші речі":"Підключіть Homebox"}/>}</Panel></div></>}
function Plan({data,loading,toggle,add}:{data:Snapshot;loading:boolean;toggle:(id:number,d:boolean)=>void;add:(k?:string)=>void}){return <section className="space-page"><header data-reveal><p>СПІЛЬНИЙ РИТМ</p><h1>План</h1><span>Усе, що варто пам’ятати сьогодні та пізніше.</span><button onClick={()=>add("task.create")}>＋ Нова справа</button></header><Panel title="Усі справи" eyebrow="VIKUNJA" badge={`${data.tasks.length} загалом`} loading={loading}><TaskList data={data} toggle={toggle} all/></Panel></section>}
function Library({data,loading,add}:{data:Snapshot;loading:boolean;add:(k?:string)=>void}){return <section className="space-page"><header data-reveal><p>ДЕ ЩО ЛЕЖИТЬ</p><h1>Речі</h1><span>Домашній каталог без пошуків по коробках.</span><button onClick={()=>add("thing.create")}>＋ Додати річ</button></header><Panel title="Домашня бібліотека" eyebrow="HOMEBOX" badge={`${data.things.length} записів`} loading={loading}>{data.things.length?<Things data={data} all/>:<Empty text="Каталог готовий до першого запису"/>}</Panel></section>}
function Coming({space,goToday}:{space:"home"|"cinema";goToday:()=>void}){const cinema=space==="cinema";return <section className="coming" data-reveal><div className="coming-art" aria-hidden="true"><i/><i/><strong>{cinema?"▷":"◇"}</strong></div><p>{cinema?"НАСТУПНА ГЛАВА":"РОЗУМНА КВАРТИРА"}</p><h1>{cinema?"Кінотеатр готується.":"Менше кнопок. Більше затишку."}</h1><span>{cinema?"Тут з’являться продовження перегляду, вечірні добірки й керування медіатекою.":"Ми додамо сценарії світла й клімату лише тоді, коли ними справді буде зручно користуватись."}</span><button onClick={goToday}>Повернутися до сьогодні</button><small>Розділ чесно позначений як майбутній — жодних декоративних даних.</small></section>}
function Panel({title,eyebrow,badge,action,loading,className="",children}:{title:string;eyebrow:string;badge?:string;action?:()=>void;loading:boolean;className?:string;children:React.ReactNode}){return <section className={`panel ${className}`} data-reveal><div className="panel-head"><div><p>{eyebrow}</p><h2>{title}</h2></div>{action?<button onClick={action} aria-label={`Додати: ${title}`}>＋</button>:badge?<span>{badge}</span>:null}</div>{loading?<Skeleton/>:children}</section>}
function TaskList({data,toggle,all=false}:{data:Snapshot;toggle:(id:number,d:boolean)=>void;all?:boolean}){return data.tasks.length?<ul className="task-list">{data.tasks.slice(0,all?20:6).map(t=><li key={t.id} className={t.done?"done":""}><button onClick={()=>toggle(t.id,!t.done)} aria-label={`${t.done?"Відкрити":"Завершити"}: ${t.title}`}>{t.done?"✓":""}</button><div><b>{t.title}</b><small>{t.due?new Date(t.due).toLocaleDateString("uk-UA"):"Без терміну"}</small></div></li>)}</ul>:<Empty text={data.connected.vikunja?"На сьогодні все зроблено":"Підключіть Vikunja"}/>}
function Things({data,all=false}:{data:Snapshot;all?:boolean}){return <div className={`things-list ${all?"all":""}`}>{data.things.slice(0,all?30:5).map(x=><div key={x.id}><span>{x.name.slice(0,1).toUpperCase()}</span><p><b>{x.name}</b><small>{x.type} · {x.quantity} шт.</small></p></div>)}</div>}
function Empty({text}:{text:string}){return <div className="empty"><span>○</span><p>{text}</p><small>Дані з’являться тут автоматично</small></div>}
function Skeleton(){return <div className="skeleton" aria-label="Завантаження"><i/><i/><i/></div>}
